spring:
  datasource:
    url: jdbc:mysql://your-production-db-url:3306/your_database_name
    username: your_database_username
    password: your_database_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080